# Generated by Django 5.0.3 on 2024-04-06 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0002_remove_sell_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='email',
            field=models.CharField(default='email', max_length=100),
        ),
    ]
