# Generated by Django 5.0.3 on 2024-04-22 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0003_agent_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent',
            name='agent',
        ),
    ]
